### ISSUE TITLE
Prefix Function

### ISSUE THREAD

**Issue by angrotheman** [bitboxde/minifier#1]
No worries - this is not a issue 😄 Awesome Plugin! What i have searched for - thanks. 
It would be great, if the plugin automatically prefix the final css file.

Edit: I think cssnext is great to implement. It transforms some new syntaxes like variables for better browser support

**Comment by bitboxrk** [comment]
Thanks for your kind words, angrotheman.

There are multiple ways to configure a prefix. For a fitting solution we need some more informations. Can you give us an example how you like to bind the files and where to configure the prefix? Or schould it just be a simple prefix without any special logic?

For example:
`{% do minifier.view.registerCssFile('<@alias>/<path/to/css-file>') %}
{% do minifier.view.registerCssFile('<@alias>/<path/to/second-css-file>') %}`

Output: `<link href="/css/min/<configuredPrefix>3f48a421fe28e0958090cc0061dec077.css?c=1548336831" rel="stylesheet">`

`<configuredPrefix>` = Set in Plugin-Options (Craft-Settings)

And we'll take a look at cssnext. Thanks for this idea! 😄

**Comment by angrotheman** [comment]
I mean prefixes like cssnext. For example:
**my css:**
--color: red;
p{color:var(--color)};

**output**
p{color:red};

This would be great for better browser support

**Comment by bitboxrk** [comment]
Because there are a lot of CSS preprocessors on the market and every one is using a different, we decided to implement it dynamicly with a little event by yourself. With this solution it's possible to implement your favorite preprocessor. Have a look at the documentation ([integrate a css preprocessor](https://github.com/bitboxde/minifier/blob/master/docs/integrate-a-css-preprocessor.md))
