### ISSUE TITLE
target file option don't work when I'm admin

### ISSUE THREAD

**Issue by angrotheman** [bitboxde/minifier#2]
I tried to implement my css but when I add a custom file name it is working on the front end but no css is loading for the admin when I have enabled the"disabled for admin" option.

**Comment by bitboxrk** [comment]
It's fixed. We solved it by removing the "@webroot"-alias with the setted alias in "JS Base URL" or "CSS Base URL" in the Plugin-Settings.

There is a bit more to do but this should work for the most cases.

**Comment by angrotheman** [comment]
Nope… still not work. Now its not working without a custom name.

**Comment by bitboxrk** [comment]
Can you send us your Plugin-Settings and the template-code where you use the minifier?

**Comment by angrotheman** [comment]
![settings](https://user-images.githubusercontent.com/44032204/52561082-a2ec9b80-2dfa-11e9-88ac-e30f33a8ede7.jpg)

Template Code: 
 {% do minifier.view.registerCssFile ("/assets/css/file1.css") %}
 {% do minifier.view.registerCssFile ("/assets/css/file2.css") %}
 {% do minifier.view.registerCssFile ("/assets/css/file3.css") %}
 {% do minifier.view.registerCssFile ("/assets/css/file4.css") %}

Front End looks good as long as I'm not logged in.
Output link if I'm logged in is: 
`<link href="/kunden/homepages/21/d656561/htdocs/craft/web/assets/css/min" rel="stylesheet">`
It is a shared hosting, yes.

Same happen if I use a custom name btw.

**Comment by bitboxrk** [comment]
That was a stupid mistake from us. :man_facepalming:

Now, with Version 1.0.2, it should be fixed... Sorry!

**Comment by angrotheman** [comment]
Nice! Works again. But if I use a custom Name it doesn't…

**Comment by bitboxrk** [comment]
What exactly do you mean with the custom name? The target file?

**Comment by angrotheman** [comment]
Yes. If i want a custom name like app.css. But the CSS don't load when I am admin and the option "disabled for admin" is on.

**Comment by bitboxrk** [comment]
I'm sorry for the late reply, but we worked a lot on the Version 2.0.0, that should fix your problem too. But be careful, we changed the usage of the Base Path and Base URL. Have a look at the new [documentation](https://github.com/bitboxde/minifier/blob/master/docs/README.md).

We also like to give you another free license for another craft project, because we reduced the price from 29$ to 19$ and we also want to thank you for your issues and support :) Please write us an E-Mail to technik@bitbox.de with your Craft ID E-Mail-Address
